### ISSUE TITLE
Safari - popover jolt  (again)

### ISSUE THREAD

**Issue by willyyang** [popperjs/react-popper#214]
Regression as this is the same issue as https://github.com/FezVrasta/react-popper/issues/131 

### CodePen demo
https://codesandbox.io/s/o40ok5wy8y

### Steps to reproduce the problem

1.  Click on Reference Element

### What is the expected behavior?

Expected the target's arrow to be in place when it's visible without the initial jolt into position

### What went wrong?

The arrow has a jerk/jolt into position

### Packages versions
 "react-popper": "^1.0.2"

Safari version 11.1.2

**Comment by larrydahooster** [comment]
Yeah, I can confirm it. Having the same behaviour in Safari. 
![sep-07-2018 11-15-22](https://user-images.githubusercontent.com/4989851/45210294-75ba2100-b28f-11e8-8e43-be541cdb5744.gif)

**Comment by willyyang** [comment]
@FezVrasta any input? :)

**Comment by FezVrasta** [comment]
I can't reproduce :-( If anyone wants to take a shot at a PR please do it

**Comment by willyyang** [comment]
:( You can see it on https://codesandbox.io/s/o40ok5wy8y ( in Safari)

**Comment by atomiks** [comment]
This doesn't happen in Safari 13 it seems. Also it probably doesn't happen in older versions with the latest major
