### ISSUE TITLE
Popper.js defined wrong as AMD dependency

### ISSUE THREAD

**Issue by KajSzy** [popperjs/react-popper#256]
### Reproduction demo

The problem is similar to #208 
Using umd build react-popper defines amd module as 'popper.js'
This makes it impossible to set properly with require config which treats extension ".js" as absolute path
`Script error for "popper.js", needed by: react-popper`

### Steps to reproduce the problem

1.  Use amd modules
2.  Define react-popper deps in require.config
`shim: { 'react-popper': { 'deps': [ 'popper' ] } }`
3.  Load react-popper

### What is the expected behavior?

Define popper dependency as 'popper'

### What went wrong?

Popper as amd dependency was defined as 'popper.js'

### Any other comments?

I know this is pretty large scale change, atm in my team we manually removed .js from UMD build.

### Packages versions

- Popper.js: 1.14.6
- react-popper: 1.3.0

**Comment by KajSzy** [comment]
Its working properly for UMD and Commonjs, but AMD with requirejs paths isn't

For working properly with AMD modules ".js" should be omitted and as I see there are plenty of issues on github both (requirejs, popperjs)
`const umdGlobals = {
  react: 'React',
  'popper': 'Popper',
};`

**Comment by FezVrasta** [comment]
I see... I don't have any control over that, it's how Rollup compiles the library.

Are you sure the solution isn't to have:

```
shim: { 'react-popper': { 'deps': [ 'popper.js' ] } }
```
?

**Comment by KajSzy** [comment]
I know and thats where requirejs kicks in [https://github.com/requirejs/requirejs/issues/1560](url)

**Comment by FezVrasta** [comment]
Oh...

if you find out a way to tell Rollup to call `popper.js` just `popper` I'll be happy to merge the PR.
