### ISSUE TITLE
Popper does not stay within the bounds of the viewport

### ISSUE THREAD

**Issue by pat-son** [popperjs/react-popper#295]
### Reproduction demo
https://stackblitz.com/edit/popper-boundary-bug?file=index.tsx

### Steps to reproduce the problem

1.  Add a popper
2.  Make the viewport scrollable and scroll the popper off the screen
3.  Notice that the popper does not move to stay in view

### What is the expected behavior?

The popper should stay within the bounds of the viewport like the default behavior

### What went wrong?

It didn't do that

### Packages versions

- Popper.js: 1.14.4
- react-popper: 1.3.3

**Comment by guillaumearm** [comment]
same issue with `popper.js@1.15.0` and `react-popper@1.3.4`

**Comment by pat-son** [comment]
Still seems like a bug, because The core popper.js (without React) acts correctly by default.

**Comment by atomiks** [comment]
> Still seems like a bug, because The core popper.js (without React) acts correctly by default.

The vanilla version works the same: https://codesandbox.io/s/intelligent-hooks-sj2rl

I am guessing `viewport` should be default for `preventOverflow` in v2 then https://github.com/popperjs/popper.js/issues/617#issuecomment-569219021

This means it matches `flip`.

**Comment by FezVrasta** [comment]
Closing since it's a Popper.js issue, not a react-popper one.
