### ISSUE TITLE
Expose offsets object via Popper component

### ISSUE THREAD

**Issue by diondiondion** [popperjs/react-popper#300]
It would be great if the Popper component didn't just expose the popper's computed `style`, but also the `offsets` object that the InnerPopper component holds in `this.state.data`.

Use case: There are cases where I want to set the max-width of my popper to the width of its reference. (Think a dropdown menu attached to a search box - you wouldn't want that menu to grow wider than the search field.) The width of the reference is stored in the offsets.reference object, but I can't get to it using react-popper. I think having access to this data could be useful in many other edge cases and troubleshooting situations.

Would you be open to a PR implementing this @FezVrasta ?

**Comment by FezVrasta** [comment]
It sounds like a good idea, thank you for the interest in a PR 🤗

**Comment by diondiondion** [comment]
Thanks, sounds good, I'll give it a go as soon as possible.

As a workaround for anyone reading this, I realised that for now it is possible to inject a custom modifier to copy whatever data you need into local state like this:

```js
const [referenceOffsets, setReferenceOffsets] = useState({});

const getReferenceModifier = {
	enabled: true,
	order: 950,
	fn: data => {
		setReferenceOffsets(data.offsets.reference);
		return data;
	},
};
```

**Comment by FezVrasta** [comment]
You could even use the `onUpdate` callback.

**Comment by diondiondion** [comment]
I probably actually have to... the extra state-setting roundtrip might be necessary as using the reference's width directly results in an initially (upon page load) misplaced popper:

**Code:**
```js
<Popper placement={activePlacement} modifiers={modifiers}>
  {({ ref, style, placement, arrowProps, offsets }) => (
    <TransitionedPopperBox
      innerRef={ref}
      style={{
        ...style,
        width:
          offsets && offsets.reference && offsets.reference.width,
      }}
    >
```

**Result:**
![image](https://user-images.githubusercontent.com/5636050/63522596-fa319e00-c4f8-11e9-94f2-325ecb403bf4.png)

So I think I'll hold off of the PR for now, unless you can think of a way to prevent this?

**Comment by FezVrasta** [comment]
I'm not sure, I should investigate it. I'm sorry!

**Comment by diondiondion** [comment]
No worries! :)

It's not as simple a problem... as of course popper might not know that you're adjusting its size at the same moment that its position is being applied. So the error kind of makes sense. I guess ideally there'd be a way to tell popper in advance about any sizing restrictions/transformations you want to apply so that they can be taken into account from the beginning.

**Comment by yunyu** [comment]
Here's my hack for this situation:

```js
  const modifiers = useMemo(() => {
    let lastReferenceWidth;

    const matchReferenceWidth = {
      enabled: true,
      order: 800,
      fn: data => {
        const referenceWidth = data.offsets.reference.width;
        if (referenceWidth !== lastReferenceWidth) {
          // Prevents things from being out of sync for some reason
          data.instance.scheduleUpdate();
        }
        lastReferenceWidth = referenceWidth;
        return {
          ...data,
          styles: {
            ...data.styles,
            width: referenceWidth
          }
        };
      }
    };

    return {
      matchReferenceWidth
    };
  }, []);
```

The `scheduleUpdate` is necessary, as things get out of sync by one event/frame without it.
