### ISSUE TITLE
UMD library doesn't load

### ISSUE THREAD

**Issue by jonchardy** [popperjs/react-popper#311]
### Reproduction demo

See https://codepen.io/jhardy/pen/gOYEdyz?editors=1000. This is a UMD problem rather than a module problem, so it can't be reproduced in the sandbox template. It looks like create-react-context and warning don't have a UMD definitions, so I'm not sure how they're meant to be loaded in a UMD environment.

### Steps to reproduce the problem

1.  Open the codepen above.
2.  Open dev tools and view the error: `Uncaught TypeError: createContext is not a function` 

### What is the expected behavior?

Library should have loaded with no errors.

### What went wrong?

Library doesn't load properly, presumably due to the missing dependencies. react-create-context and warning don't have UMD distributables, so they may need to be bundled.

### Packages versions

- Popper.js: 
- react-popper: 1.3.4

**Comment by kristofferlund** [comment]
When I build my project with react-popper 1.3.7 I get something similar:
```
Error: 'default' is not exported by node_modules/create-react-context/lib/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/react-popper/lib/esm/Manager.js (5:7)
3: import _defineProperty from "@babel/runtime/helpers/defineProperty";
4: import * as React from 'react';
5: import createContext from 'create-react-context';
          ^
```

**Comment by FezVrasta** [comment]
May someone take a look at react-popper@2.2.0? I removed `create-react-context` and bundled `warning` and `react-fast-compare`, so everything should work now.

**Comment by patrickedqvist** [comment]
This problem still exists in the 1.3.11 version
