### ISSUE TITLE
Incorrect popover location

### ISSUE THREAD

**Issue by acambas** [popperjs/react-popper#324]
### Reproduction demo

After the recent update from 1.3.6 to 1.3.7 of react-popper, I'm having an issue where the popup is not appearing at the correct place, the issue doesn't happen with 1.3.6 at all.
I can't show the exact code since it's proprietary but here are the images with the bug.

The image with the issue(1.3.7 version), the "ADD ADULT" popover should open around the gray circle with a plus icon
https://ibb.co/0Xdb3H7

The image with no issue
https://ibb.co/yY3RMM5

**Comment by FezVrasta** [comment]
I can’t help without a reproducible demo (codepen, codesandbox, etc). I’m sorry.

**Comment by movahedan** [comment]
I'm facing the same problem, on very first render, "style" object set a wrong "transform" attribute. But it's pretty fun that when I scroll the page, "style" object updates and the popover take place in correct position, I tried "scheduleUpdate" and change "modifier" object, but the problem remained. I can scroll the page manually when open state changes (as I told above), but It's a hot fix. Can you give me an advice @FezVrasta  ?

**Comment by singharpit94** [comment]
This issue can be because of this [commit](https://github.com/popperjs/popper.js/pull/790/files)
