### ISSUE TITLE
Popper instance not updating with `espaceWithReference` modifier in v1.3.7

### ISSUE THREAD

**Issue by Harsh1796** [popperjs/react-popper#334]
### Reproduction demo

The following are the forks related to the issue:

Fork with the issue: https://codesandbox.io/s/react-popper-bug-v137-elm3p
Fork without the issue: https://codesandbox.io/s/react-popper-bug-v136-4n096

### Steps to reproduce the problem

1. Add an element(<div/> maybe) above the `reference element` and place the `popper element` to the bottom of `reference element`.  
2.  Add `espaceWithReference: true` to prevent overflow modifier in Popper.
3.  Try to Add elements to the `<div/>` above the `reference element`.
4.  The popper wouldn't update it's instance. The `reference element` will shift with addition to elements in the `<div/> above it but the `Popper` won't update and remain to the same position.

[Sandbox](https://codesandbox.io/s/react-popper-bug-v137-elm3p)

### What is the expected behavior?

In react-popper version 1.3.6 , referring to step 4 from above. The Popper would update it's instance and would update it's position along with the reference element.

[Sandbox](https://codesandbox.io/s/react-popper-bug-v136-4n096)

Would have expected to have a similar behaviour in the new version. 
Couldn't find the tag related to 1.3.7 release. 

### What went wrong?

Update to 1.3.7 broke the behaviour of my application. 

### Any other comments?

This issue might be because of 47677e9b251a7bc156e82d32b37c6f07d90f3e02

### Packages versions

- Popper.js: 
- react-popper: 1.3.7

**Comment by FezVrasta** [comment]
That's expected, previously the popper was instantiated on every React rerender, but it wasn't the way it was designed to work.

You need to manually trigger a popper update to achieve what you're after. You can  either use a `useEffect` or a mutation observer.
