### ISSUE TITLE
Question:  Version 1.3.7 not found in Releases tab

### ISSUE THREAD

**Issue by greg-a-smith** [popperjs/react-popper#335]
This isn't an issue by the standard definition, but rather a question.  I see the `package.json` is updated to version 1.3.7 and that version exists on npmjs.com, however, I don't see it in the Releases tab nor do I see a tag for that version.  Seems like an oversight, right?

**Comment by FezVrasta** [comment]
Hi, the only change included in 1.3.7 was the addition of the `funding` package.json field, 1.3.6 is functionally identical so I didn't cut a new github release.
