### ISSUE TITLE
Overflow when using arrowProps.

### ISSUE THREAD

**Issue by MortenHofft** [popperjs/react-popper#338]
### Reproduction demo
Overflows on the left when setting position bottom
https://codesandbox.io/s/react-popper-v1x-issue-template-zuh2j

Solved by removing the arrowProps.ref
https://codesandbox.io/s/react-popper-v1x-issue-template-1iquk

### Steps to reproduce the problem

1.  Look at the purple box, it overflows in one example, but not the other

### What is the expected behavior?

I *think* it is a bug that it overflows. I do not understand why the arrow props would change the position.

### What went wrong?
It overflows

### Any other comments?
Thank you for a nice library

I had started with a demo in my own sandbox https://codesandbox.io/s/delicate-haze-er90q based on the README example. 
The main difference is that it is using the latest version of the react and react-popper.

### Packages versions

- Popper.js: The one specified in your codesandbox as a required template
- react-popper: The one specified in your codesandbox as a required template

**Comment by FezVrasta** [comment]
This is fixed in `react-popper@2`
https://codesandbox.io/s/react-popper-v1x-issue-template-9htno
