### ISSUE TITLE
forceUpdate is not defined

### ISSUE THREAD

**Issue by Slapbox** [popperjs/react-popper#342]
### Reproduction demo
None at present.

### Steps to reproduce the problem

1.  Create virtual element to reference (not sure this matters)
2.  On the inner popper component, which is passed the props from ` <Popper />`, try to access `this.props.forceUpdate` - it will be `undefined`

### What is the expected behavior?
`forceUpdate` should exist as per [PopperJS v2 docs](https://popper.js.org/docs/v2/migration-guide/#8-update-method-names).

### What went wrong?

`this.props.forceUpdate` is `undefined`

![image](https://user-images.githubusercontent.com/6835891/78459716-e5210e00-7688-11ea-89d0-bb0d2ff442a3.png)

### Packages versions

- Popper.js: `2.2.0`
- react-popper: `2.0.0`

**Comment by FezVrasta** [comment]
The docs still need some work to reflect the Popper 2 update ☹️

**Comment by Slapbox** [comment]
@FezVrasta thanks for your reply! I'm a bit confused, React-Popper _should_ expose `forceUpdate()`, right? `v1.x` passed both `scheduleUpdate` and `update` as props if I'm not mistaken.

**Comment by FezVrasta** [comment]
Yes I’m confused too 😂 I’ll take a look tomorrow.

**Comment by FezVrasta** [comment]
2.1.0 exposes `forceUpdate`

**Comment by Slapbox** [comment]
@FezVrasta thanks for the prompt attention! Unfortunately the issue persists for me with `react-popper` and `@popperjs/core` each at `2.2.0`. Thoughts?

**Comment by FezVrasta** [comment]
May you please provide a reproduction example on codesandbox or codepen please?

**Comment by Slapbox** [comment]
Hey @FezVrasta I won't have time to put together something more robust, but here's sort of our usage looks like:

```js
export const PopperRoot = props => {
  return (
    <Popper
      {...props}>
      {({ ref, ...popperProps }) => (
        <InnerPopper innerRef={ref} {...props} {...popperProps} />
      )}
    </Popper>
  );
};



export class InnerPopper extends React.Component {
  componentDidMount() {
    const { forceUpdate, registerPopperFunctions } = this.props;
    //  Register functions for popper management in parent
    registerPopperFunctions({
      forceUpdatePopper: forceUpdate, //  forceUpdate will not be defined at this time
    });
  }
}
```

So instead we're now checking if `forceUpdate` is defined in `componentDidUpdate` and running our `registerPopperFunctions` at the point `forceUpdate` is available. It takes like 15 lines instead of 3 and has to run on every update, but it's still pretty lightweight and it works well enough.
