### ISSUE TITLE
VirtualReference not calling getBoundingClientRect as expected

### ISSUE THREAD

**Issue by Slapbox** [popperjs/react-popper#356]
### Reproduction demo
None right now. Sidenote, issue template links to code sandboxes for `v0` and `v1`, but not `v2`.

### Steps to reproduce the problem
This is a very basic version of how the updates are being called. Only creates an issue above `2.1.0`.

```js
  componentDidMount() {
    const { update } = this.props;
    this.updatePopper = _debounce(() => {
      // ... additional logic that conditionally returns early
      update();
    }, 25);
  }

  componentDidUpdate() {
    this.updatePopper.cancel();
    this.updatePopper();
  }
```
### What is the expected behavior?

The `getBoundingClientRect` method of the `VirtualReference` should be called when `update` is called.

### What went wrong?
After upgrading from `2.1.0` to `2.2.x`, `getBoundingClientRect` is only called at startup, and then not anymore. This could be related to our specific implementation, but it worked beautifully in `2.1.0`.

### Packages versions

- Popper.js: `2.2.0` (also occurs with `2.3.x`)
- react-popper: `2.2.2`

**Comment by FezVrasta** [comment]
Without a repro it’s going to be difficult to help you

**Comment by Slapbox** [comment]
Unfortunate, but not unexpected. I understand .Thanks for your reply @FezVrasta.

If I was sure about how to reproduce it I'd try to find the time, but since I'm not and since `2.1.x` works perfectly, perhaps someone else will come along with the same issue and make a repro.

**Comment by FezVrasta** [comment]
I updated the template to use v2, feel free to use it to prepare a repro.

https://codesandbox.io/s/relaxed-northcutt-7mwkynymlq

For now I'll close this issue, I'll reopen it once a repro is provided.
