### ISSUE TITLE
Hook parameters are not documented

### ISSUE THREAD

**Issue by knpwrs** [popperjs/react-popper#360]
When I look at https://popper.js.org/react-popper/v2/hook/ I see documentation about what is returned from the hook but nothing about what I should pass into the hook! I wound up using the TypeScript types though I also realize there's an example at https://popper.js.org/react-popper/v2/ but it really seems like the hook parameters should be documented on the hook page.

**Comment by FezVrasta** [comment]
I'd rather have all the documentation in a single place, if we place it in the readme, and in the docs, we need to update it twice
