### ISSUE TITLE
Inconsistent and incorrect arrow position

### ISSUE THREAD

**Issue by jonrimmer** [popperjs/react-popper#364]
I am trying to use the new `usePopper` hook, but I am running into problems where the arrow is sometimes not correctly positioned when using bottom placement. 

### Reproduction demo

https://codesandbox.io/s/youthful-minsky-frghk?file=/src/App.js

### Steps to reproduce the problem

1.  Hover the title

### What is the expected behavior?

The arrow should appear in the centre of the tooltip.

### What went wrong?

The arrow appears on the left of the tooltip.

### Any other comments?

Changing to use a styled-component prop to hide/show the tooltip fixes the problem on first load, but it reoccurs when a reload occurs due to either HMR or manually using the codesandbox refresh button:

https://codesandbox.io/s/relaxed-nobel-dttib?file=/src/App.js

### Packages versions

- Popper.js: 2.4.0
- react-popper: 2.2.3

**Comment by FezVrasta** [comment]
Your arrow element must have some width and height.

https://codesandbox.io/s/gracious-goldwasser-b375d?file=/src/App.js

**Comment by jonrimmer** [comment]
@FezVrasta Thanks, but suggestion doesn't seem to really fix the issue, it just shifts it around a bit. See what happens if I modify your demo to change the placement to `right` and set the tooltip visible on start:

https://codesandbox.io/s/dawn-feather-efw7s?file=/src/App.js

Again, the arrow is rendered in the wrong place. If you hide and reshow the tooltip (by hovering no and off) you will see the arrow position change. I  am seeing many similar problems in my real project.

**Comment by FezVrasta** [comment]
It's a problem with your CSS, Popper is positioning the real arrow element fine, but you need to make sure your `::before` pseudo-element fits its container (the real arrow)

![image](https://user-images.githubusercontent.com/5382443/82589117-f4f2a400-9b9b-11ea-831e-9d99cb7a106e.png)
