### ISSUE TITLE
Browser hangs when passing function to offset modifier (in usePopper hook)

### ISSUE THREAD

**Issue by reywright** [popperjs/react-popper#366]
### CodeSandbox demo

https://codesandbox.io/s/morning-meadow-rnoxy

### Steps to reproduce the problem

1.  Pass a function to the `offset` modifier.

(this has already been done in the sandbox, just click the button)

### What is the expected behavior?

That it shows the popover and works, the same as if the modifier was  `offset: [0, 0]`

### What went wrong?

The browser / iframe will hang and the popover won't show.

### Any other comments?

Note: again, the following works perfectly fine:

```         
options: {
  offset: [0, 0]
}
```

I'm unclear why the function breaks things here.

Documentation is here: https://popper.js.org/docs/v2/modifiers/offset/#distance-1

To note: documentation shows an example using `createPopper`, not `usePopper` (not sure if there's a difference).

**Comment by FezVrasta** [comment]
I think it’s this issue

https://github.com/popperjs/react-popper/issues/363

We probably need to add some documentation

**Comment by reywright** [comment]
Both of the solutions in that ticket fix my issue (either defining the modifier function outside the component, or using `useMemo`). Thanks @FezVrasta 

In terms of documentation, I sort of wonder where exactly it would go. It doesn't seem to fit on the offset page, and also those docs are for using without React. Maybe some sort of "gotchas / tips" section for the React documentation, and then it could go in there?

**Comment by FezVrasta** [comment]
I added a FAQ section https://popper.js.org/react-popper/v2/faq/
