### ISSUE TITLE
Add engines to package.json

### ISSUE THREAD

**Issue by MichaelDeBoey** [popperjs/react-popper#377]

**Comment by FezVrasta** [comment]
I don't think that's something useful for a frontend project, according to the [npm documentation](https://docs.npmjs.com/files/package.json#engines) it's meant to be used to `specify the version of node that your stuff works on`, this project is not dependant by any node version.

**Comment by MichaelDeBoey** [comment]
@FezVrasta It's not required, but it helps to have the minimum supported/tested Node version in `package.json`

It's mostly the minimum `node` version you're testing against.

https://github.com/jaydenseric/apollo-upload-client/blob/219002c88a34aade4c0fd1f89865f560ac730804/package.json#L32-L34

https://github.com/facebook/react/blob/147179ae82039f38fa1a9a72402f578af8fb3ea3/packages/react/package.json#L28-L30

**Comment by FezVrasta** [comment]
I'm not testing against any node version, the package is a client-side code.
