### ISSUE TITLE
How to handle popper when there is an header in position fixed

### ISSUE THREAD

**Issue by Filippinifra** [popperjs/react-popper#385]
### Reproduction demo

<img width="442" alt="Screenshot 2020-09-13 at 12 30 00" src="https://user-images.githubusercontent.com/31794601/93015826-dab25b00-f5bc-11ea-81a8-65148091b8a8.png">

### Steps to reproduce the problem

It's so easy to reproduce it.
Take a top position fixed element and an element that scrolls inside the page referred to the popper (top placement).
When popper is near the top zone of the page it collides with fixed element (it can be over or below the fixed element for example depending to z-index).

### What is the expected behavior?

I want the popper knows that he cannot be in the former top px of the page and when it collides with header its replacement is bottom.

### Packages versions

- Popper.js: 2.4.4
- react-popper: 2.2.3

**Comment by FezVrasta** [comment]
Ciao, you can set the `padding` option in the preventOverflow modifier.

https://popper.js.org/docs/v2/modifiers/prevent-overflow/#padding
