### ISSUE TITLE
The legacy class components are not working correctly in v2.x

### ISSUE THREAD

**Issue by harryfino** [popperjs/react-popper#387]
The legacy class components are not working correctly when updating from v1.3.7 to v2.x. I'm using the `referenceElement` property in the `<Popper>` component and something isn't working correctly.

### Reproduction demo

This link shows a working example of Popper as a tooltip when you hover over the word "editing".
https://codesandbox.io/s/legacy-popper-usage-m5v83?file=/src/App.js

When you change to `react-popper` to v2.x in the dependencies on the left, this example starts failing on mouseover with the error `Cannot read property 'x' of undefined`.

### Steps to reproduce the problem

1.   Hover over the word "editing" and observe the correct behavior using v1.3.7 of `react-popper`
![Screen Shot 2020-09-22 at 1 58 21 PM](https://user-images.githubusercontent.com/1643512/93919661-febc1d80-fcdb-11ea-9752-2f633d38461e.png)

2.  Switch dependencies to v.2.2.3 of `react-popper`.
![Screen Shot 2020-09-22 at 1 53 24 PM](https://user-images.githubusercontent.com/1643512/93918920-06c78d80-fcdb-11ea-9e2a-5524ff26e4ce.png)

3.  Hover over the word "editing" and observe the error message.
![Screen Shot 2020-09-22 at 2 01 04 PM](https://user-images.githubusercontent.com/1643512/93919726-15fb0b00-fcdc-11ea-919f-d1081a95e97e.png)

### What is the expected behavior?

The expected behavior is that this would show the Popper in the correct position without raising an error.

### Packages versions

- Popper.js: v2.4.4
- react-popper: v1.3.7 & v2.2.3

**Comment by harryfino** [comment]
It looks like this error is caused by `top-middle` not being supported in v2. I switched to `top` instead and it worked correctly. I'm closing the issue, but keeping this around in case someone else runs into this problem.

**Comment by FezVrasta** [comment]
`top-middle` was never supported, the placements have always been `top-start`, `top`, `top-end`

**Comment by harryfino** [comment]
Maybe it was a typo that I made a long time ago, but I was never punished for it in v1 and it placed the popper in the correct position. The error handling is v2 did not tell me this was invalid and sent me on a goose chase for hours. Maybe something like this would go a long way?

```
Popper.propTypes = {
     placement: PropTypes.oneOf([
          'top-start',
          'top',
          'top-end',
          ...
     ])
};
```

In my components, this helps prevents me from passing in the wrong text.

Anyway, cheers and thank you for a great library!

**Comment by FezVrasta** [comment]
We ship Flow and TS type defs that should warn you about this, PropTypes are basically deprecated at this point.
