### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by mtmacdonald** [popperjs/react-popper#392]
Hi, please can we have support for React 17 so I don't get this npm warning upon npm install in my React 17 projects. Thanks!

npm WARN react-popper@1.3.7 requires a peer of react@0.14.x || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by FezVrasta** [comment]
https://github.com/popperjs/react-popper/releases/tag/v2.2.4 supports React 17
