### ISSUE TITLE
Rendering 3 times on load every time

### ISSUE THREAD

**Issue by tounsoo** [popperjs/react-popper#396]
### Reproduction demo

https://codesandbox.io/s/condescending-stallman-e81yy?file=/src/App.js

### Steps to reproduce the problem

1.  open console
2.  refresh the rendered page 
3.  you see 'rendered' being logged 3 times

### What is the expected behavior?
Seeing only one log of 'rendered'

### What went wrong?
Looks like its rendering 3 times by default

### Any other comments?
Is this normal behavior?

### Packages versions

- Popper.js: 2.5.3
- react-popper: 2.2.3

**Comment by OmarMorales71** [comment]
@tounsoo Hello! is this happening in all components? or do you know about specific components with this behavior?

**Comment by tounsoo** [comment]
@OmarMorales71 Not sure what you mean. The Codesandbox example has only one component.

**Comment by tu4mo** [comment]
It's expected because of setReferenceElement and setPopperElement are called after initial render.

**Comment by tounsoo** [comment]
True, is there another way to use `usePopper` so that we don't have to rely on useState, hopefully avoiding additional renders?

**Comment by FezVrasta** [comment]
That's because we use ref callbacks, so any time one is set the component re-renders. This is needed because we need to know when a reference or popper element changes identity.
