### ISSUE TITLE
React 17 support for 1.x

### ISSUE THREAD

**Issue by kyletsang** [popperjs/react-popper#401]
Hi, is it possible to release a 1.x version with React 17 support (unsure if it's just a matter of allowing v17 in peer deps)?

We're currently using 1.3.6 over at Reactstrap, and are currently unable to migrate to v2 anytime soon.

### Packages versions

- react-popper: 1.3.6

**Comment by FezVrasta** [comment]
Updating the semver range should be enough, feel free to send a PR! 🙌

**Comment by kyletsang** [comment]
Sounds good @FezVrasta.  I noticed there's no branch for 1.x.  Could you create that for me and I'll make a PR for it?   Thanks!

**Comment by FezVrasta** [comment]
Pushed 1.x
