### ISSUE TITLE
some thing error for npm ?

### ISSUE THREAD

**Issue by welkinwong** [popperjs/react-popper#404]
when i install the latest version, i get the 1.3.8

![image](https://user-images.githubusercontent.com/6650440/108110769-b2c8a580-70ce-11eb-8d13-4b76fcfc5241.png)

**Comment by jzrandall** [comment]
I just came here to ask the same thing.

**Comment by FezVrasta** [comment]
Sorry for the issue, I published a new 1.x version and was automatically set as latest, it should be fixed now.
