### ISSUE TITLE
Need to upgrade @poperjs/core version to use Arrow modifier padding function

### ISSUE THREAD

**Issue by WeiLi512** [popperjs/react-popper#407]
### What is the expected behavior?

I want to use the padding function in the custom arrow modifier.
https://popper.js.org/docs/v2/modifiers/arrow/#padding
 
### What went wrong?
I can't use custom arrow padding function feature in react-popper

### Packages versions

- Popper.js: 2.8.3
- react-popper: 2.2.4

**Comment by FezVrasta** [comment]
@popperjs/core is a peer dependency, you can update it independently

**Comment by WeiLi512** [comment]
I tried that but It seemed like working
But didn't pass popper and reference parameters to the Padding Function. only passed placement parameter.

**Comment by FezVrasta** [comment]
That was a bug with Popper, install 2.8.4 to fix it

**Comment by WeiLi512** [comment]
I can see you just release the new version
Can I install it with NPM or Yarn now?
