### ISSUE TITLE
Resizing or Scrolling bug on calculating position

### ISSUE THREAD

**Issue by amerllica** [popperjs/react-popper#408]
When I change the size of window or scrolling the page `react-popper` can't calculate position properly, I saw [this issue](https://github.com/popperjs/react-popper/issues/354), maybe my issue is related to it in reverse. because for first initializing it works properly by right after change window size or scrolling `react-popper` unable to calculate position properly.

### Reproduction demo

I thought it is my issue, but I saw [an example](https://codesandbox.io/s/musing-grass-nvpt0) on CodeSandBox and it has this issue too. [this sand box](https://codesandbox.io/s/musing-grass-nvpt0) is completely ready, just see the dropdown works properly, then resize the window of sand box an retry to click the button, you can see the dropdown is not in right place.

### Steps to reproduce the problem

1.  open [this sand box](https://codesandbox.io/s/musing-grass-nvpt0)
2.  click the button and you see `react-popper` works properly. (close the dropdown)
3.  resize the window of sand box
4. click the button again
5. you can see the dropdown is not in a correct position

### What is the expected behavior?

being in correct place

### What went wrong?

the popper menu is not in a correct place after resizing or scrolling the page

### Any other comments?

I wanna leave this awesome library, I just report to help the community

### Packages versions

- Popper.js: "@popperjs/core": "^2.6.0",
- react-popper: "react-popper": "^2.2.4",

**Comment by atomiks** [comment]
You should conditionally render the element, not use `display` in the CSS.

```js
      {visible && (
        <div ref={setPopper} style={styles.popper} {...attributes.popper}>
          <DropdownContainer style={styles.offset} visible={visible}>
            <DropdownItem>Element</DropdownItem>
            <DropdownItem>Element</DropdownItem>
            <DropdownItem>Element</DropdownItem>
          </DropdownContainer>
        </div>
      )}
```

**Comment by FezVrasta** [comment]
Or if you want to use the `display` property you must make sure to call `popper.update()` after the visibility is changed.

**Comment by nixjs** [comment]
Config the strategy: 'fixed'. A issue will resolve.
```typescript
createPopper(reference, popper, {
  strategy: 'fixed',
});
```
