### ISSUE TITLE
Regression in 1.3.10?

### ISSUE THREAD

**Issue by ciprianmiclaus** [popperjs/react-popper#409]
Release 1.3.10 (https://www.npmjs.com/package/react-popper/v/1.3.10) seems to have re-introduced an issue that was fixed in 1.3.7: https://github.com/popperjs/react-popper/pull/320
An infinite loop when zoom is at 75%. I can reproduce locally with 1.3.10, not with 1.3.7

**Comment by FezVrasta** [comment]
I think the only change introduced by 1.3.10 is a replacement library for the create-react-context one that didn't support React 17. I don't think it can be the issue.

**Comment by ciprianmiclaus** [comment]
Doing a diff between the index.umd.js in react-popper1.3.7 and react-popper1.3.10, I can clearly see 1.3.10 is missing the deepEqual comparison on props.modifiers (which was the fix for the infinite loop). Perhaps 1.3.10 was based on a previous version?

**Comment by FezVrasta** [comment]
Could be, my iMac hard drive is misbehaving lately, I lost 1 week of saved files the other day...

Is the `v1.x` branch okay?

**Comment by ciprianmiclaus** [comment]
No, it's not, it seems it was branched off 1.3.6, not 1.3.7 - that's the problem.

**Comment by FezVrasta** [comment]
🤔

**Comment by FezVrasta** [comment]
I can't find the commit, could you cherry pick it in a new branch and send a PR please?

**Comment by ciprianmiclaus** [comment]
Can you add me as a contributor?

**Comment by FezVrasta** [comment]
There's no need, fork the repository and work on the work, then you can send a PR to merge into this one.

**Comment by ciprianmiclaus** [comment]
Here's the missing commit: 
https://github.com/popperjs/react-popper/commit/47677e9b251a7bc156e82d32b37c6f07d90f3e02

**Comment by FezVrasta** [comment]
Umh that commit is for the 2.x version, it was never included in 1.x

**Comment by FezVrasta** [comment]
1.3.11 should include it

**Comment by ciprianmiclaus** [comment]
Thank you!
