### ISSUE TITLE
Nested poppers using portals not updating position

### ISSUE THREAD

**Issue by zbrogz** [popperjs/react-popper#412]
### Reproduction demo

https://codesandbox.io/s/nostalgic-hugle-9n0ns?file=/src/Menu.js

### Steps to reproduce the problem

1.  Scroll down to the first reference element, "menu anchor"
2.  Click on "menu anchor" to open the first popper
3.  Click on "first submenu anchor" to open the next popper
4. Scroll the page and the nested popper's position does not update with it's reference element ("first submenu anchor")

### What is the expected behavior?

The nested poppers' position should update with the reference element as the page is scrolled.

### What went wrong?

Removing `position: absolute` or `overflow: scroll` from the parent div is a workaround.

### Any other comments?

It's likely that this is an issue with `@popperjs/core`, not `react-popper`.

![Kapture 2021-03-24 at 17 39 47](https://user-images.githubusercontent.com/319162/112397979-cd42ff80-8cc8-11eb-84fa-e98390525ca6.gif)

### Package versions

- @popperjs/core: 2.9.1
- react-popper: 2.2.4

**Comment by FezVrasta** [comment]
The issue seems indeed to be on @popperjs/core, could you open an issue there and update the example to not use any 3rd party dependency (such as React or react-popper)? Thanks
