### ISSUE TITLE
Wrong arrow positionning

### ISSUE THREAD

**Issue by Dataxelio** [popperjs/react-popper#416]
### Reproduction demo

https://codesandbox.io/s/festive-lichterman-go5wj?file=/src/App.tsx

### Steps to reproduce the problem

Please see codesandbox.

### What is the expected behavior?

Arrow should be positionned correctly with the translate css property available on styles.arrow

### What went wrong?

![screenshot_20210420](https://user-images.githubusercontent.com/62846298/115422456-343ad200-a1fd-11eb-94df-8cd6bb0b8195.png)

### Any other comments?

Maybe I miss something but I expect at least to have the correct positionning out of the box with styles.arrow.
In my code, I also try to add a rotate(45deg) to the transform available on styles.arrow. But this is an another point.

### Packages versions

- Popper.js: 2.0.4
- react-popper: 2.2.5

**Comment by FezVrasta** [comment]
Hi, that's not how it works, popper only computes the arrow offset.

Take a look at the tutorial on popper.js.org to see a full example
