### ISSUE TITLE
Arrow missing

### ISSUE THREAD

**Issue by simplenotezy** [popperjs/react-popper#418]
### Reproduction demo

Described here by another user 2 months ago: https://stackoverflow.com/questions/66037355/what-am-i-missing-when-using-react-poppers-usepopper-hook-to-generate-an-arro - I face the same issue

### Steps to reproduce the problem

1.  Copy base example from https://popper.js.org/react-popper/v2/
2.  Run in Next.js ( not sure if this is a required step )
3.  See that arrow is missing

### What is the expected behavior?

Arrow should appear

### What went wrong?

No arrow - seems like it has no width/height.

![image](https://user-images.githubusercontent.com/3786627/115958852-89325d00-a509-11eb-9b43-88312ba75171.png)

### Packages versions

- Popper.js: ^2.9.2
- react-popper: ^2.2.5

**Comment by FezVrasta** [comment]
Popper doesn't provide any style, please follow the tutorial https://popper.js.org/docs/v2/tutorial/
